version: '3.8'

services:
  tauri_frontend_vue:
    container_name: tauri_frontend_vue
    image: shortpoet/vite
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    working_dir: /usr/src/app
    ports:
      - '1420:1420'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - tauri_backend_rust
    networks:
      - app-network

  tauri_backend_rust:
    container_name: tauri_backend_rust
    image: rust:1.67.1
    restart: always
    networks:
      - app-network

networks:
  app-network:
